/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as JokesImport } from "./routes/jokes";
import { Route as IndexImport } from "./routes/index";
import { Route as JokesIndexImport } from "./routes/jokes.index";

// Create/Update Routes

const JokesRoute = JokesImport.update({
  id: "/jokes",
  path: "/jokes",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const JokesIndexRoute = JokesIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => JokesRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/jokes": {
      id: "/jokes";
      path: "/jokes";
      fullPath: "/jokes";
      preLoaderRoute: typeof JokesImport;
      parentRoute: typeof rootRoute;
    };
    "/jokes/": {
      id: "/jokes/";
      path: "/";
      fullPath: "/jokes/";
      preLoaderRoute: typeof JokesIndexImport;
      parentRoute: typeof JokesImport;
    };
  }
}

// Create and export the route tree

interface JokesRouteChildren {
  JokesIndexRoute: typeof JokesIndexRoute;
}

const JokesRouteChildren: JokesRouteChildren = {
  JokesIndexRoute: JokesIndexRoute,
};

const JokesRouteWithChildren = JokesRoute._addFileChildren(JokesRouteChildren);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/jokes": typeof JokesRouteWithChildren;
  "/jokes/": typeof JokesIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/jokes": typeof JokesIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/jokes": typeof JokesRouteWithChildren;
  "/jokes/": typeof JokesIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/jokes" | "/jokes/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/jokes";
  id: "__root__" | "/" | "/jokes" | "/jokes/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  JokesRoute: typeof JokesRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JokesRoute: JokesRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/jokes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/jokes": {
      "filePath": "jokes.tsx",
      "children": [
        "/jokes/"
      ]
    },
    "/jokes/": {
      "filePath": "jokes.index.tsx",
      "parent": "/jokes"
    }
  }
}
ROUTE_MANIFEST_END */
